In [ ]:
import csv
import pandas as pd

file_path = './data/osdg.csv'

df = pd.read_csv(file_path, sep='\t')
df

,doi,text_id,text,sdg,labels_negative,labels_positive,agreement
0,10.6027/9789289342698-7-en,00021941702cd84171ff33962197ca1f,"From a gender perspective, Paulgaard points ou...",5,1,8,0.777778
1,10.18356/eca72908-en,00028349a7f9b2485ff344ae44ccfd6b,Labour legislation regulates maximum working h...,11,2,1,0.333333
2,10.1787/9789264289062-4-en,0004eb64f96e1620cd852603d9cbe4d4,The average figure also masks large difference...,3,1,8,0.777778
3,10.1787/3726edff-en,0005d3e8b213d9e2cb967666e1aca2e9,Applied research is directed “primarily toward...,9,3,6,0.333333
4,10.1787/5k9b7bn5qzvd-en,0006a887475ccfa5a7f5f51d4ac83d02,The extent to which they are akin to corruptio...,3,1,2,0.333333
...,...,...,...,...,...,...,...
42630,10.6027/9789289347204-5-en,fffc6ac25f325ab949f92d3563194b3f,Since the full capacity is not likely to be ut...,7,5,4,0.111111
42631,10.1017/S0020589318000167,fffdf2bc9ac129ed95ef7727584aa74b,This article notes the judgment in Sophocleous...,16,2,4,0.333333
42632,10.1787/9789264186378-8-en,fffe58dae29de6b843aff09b6e2f77f0,Groundwater quality can also be affected by co...,6,0,3,1.000000
42633,10.1787/9789264191761-en,ffff357a454e2d7544f765cf2660e684,Remedier a ces lacunes est la recommandation p...,2,4,5,0.111111
42634,10.18356/39dd1e2e-en,ffffcd9cc3f5d943560fe90fb9354ba5,The three diseases that resulted in the greate...,3,1,7,0.750000

In [ ]:
df_osdg = df[['text', 'sdg']]

df_osdg

                                                    text  sdg
0      From a gender perspective, Paulgaard points ou...    5
1      Labour legislation regulates maximum working h...   11
2      The average figure also masks large difference...    3
3      Applied research is directed “primarily toward...    9
4      The extent to which they are akin to corruptio...    3
...                                                  ...  ...
42630  Since the full capacity is not likely to be ut...    7
42631  This article notes the judgment in Sophocleous...   16
42632  Groundwater quality can also be affected by co...    6
42633  Remedier a ces lacunes est la recommandation p...    2
42634  The three diseases that resulted in the greate...    3

[42635 rows x 2 columns]

In [7]:
df_osdg.groupby('sdg').count()

     text
sdg
1    2734
2    2457
3    2689
4    3740
5    4338
6    2815
7    3048
8    1509
9    2510
10   2244
11   2277
12   1108
13   2102
14   1141
15   2472
16   5451

- osdg 데이터에는 SDG-17이 존재하지 않으므로, datahub의 데이터 중 SDG-17에 해당하는 데이터를 추가

In [ ]:
df_hub = pd.read_csv('data_hub.csv')
df_hub.head()

,text,SDG-01,SDG-02,SDG-03,SDG-04,SDG-05,SDG-06,SDG-07,SDG-08,SDG-09,SDG-10,SDG-11,SDG-12,SDG-13,SDG-14,SDG-15,SDG-16,SDG-17
0,UNECE Releases 44 Recommended Climate Indicato...,1,1,0,0,0,1,1,0,0,0,1,0,1,0,1,0,0
1,Largest Source of Lead Pollution Phased Out in...,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
2,VNR Update: 15 Countries Planning to Participa...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
3,SDG Moment Will Provide Reality Check with Nin...,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1
4,"Biodiversity Framework Will Need Finance, Capa...",0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0

In [ ]:
sdg = [f'SDG-{str(i).zfill(2)}' for i in range(1, 18)]

columns_to_select = ['text'] + sdg
df_hub = df_hub[columns_to_select]

df_hub[sdg].sum()

SDG-01    2562
SDG-02    1922
SDG-03    1949
SDG-04    1193
SDG-05    1802
SDG-06    1617
SDG-07    1865
SDG-08    2035
SDG-09    1589
SDG-10    2049
SDG-11    1526
SDG-12    1632
SDG-13    3701
SDG-14    1448
SDG-15    2197
SDG-16    1882
SDG-17    4484
dtype: int64

In [11]:
sdg_17_only = df_hub[df_hub['SDG-17'] == 1]

other_sdgs = [sdg for sdg in sdg if sdg != 'SDG-17']
sdg_17_plus_one_other = sdg_17_only[other_sdgs].sum(axis=1) <= 1

sdg_17_plus_one_other_count = sdg_17_plus_one_other.sum()
sdg_17_plus_one_other_count

1419

In [14]:
sdg_17_plus_one_other_rows = sdg_17_only[sdg_17_plus_one_other]
sdg_17_plus_one_other_rows

,text,SDG-01,SDG-02,SDG-03,SDG-04,SDG-05,SDG-06,SDG-07,SDG-08,SDG-09,SDG-10,SDG-11,SDG-12,SDG-13,SDG-14,SDG-15,SDG-16,SDG-17
2,VNR Update: 15 Countries Planning to Participa...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
12,Consultation Underway on New Indicator for SDG...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
15,2021 Population Data Sheet Highlights Declinin...,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
29,ECOSOC President Offers Preview of 2022 Sessio...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
32,Peer Exchange Identifies Components of Good Ci...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9138,UNICEF Highlights Young Climate Heroes as Winn...,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1
9143,GIS for a Sustainable World: Bringing the Powe...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
9150,The Essence of Leadership for Achieving the Su...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
9161,Localizing the SDGs at the Grassroots in Niger...,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
9170,Generation 2030: Have Your Say The Generation ...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [17]:
# SDG-17==1
sdg_17_only = df_hub[df_hub['SDG-17'] == 1]

# other sdgs sum==0
sdg_sum_zero = sdg_17_only[other_sdgs].sum(axis=1) == 0
sdg_sum_zero_rows = sdg_17_only[sdg_sum_zero]

# other sdgs sum==1
sdg_sum_one = sdg_17_only[other_sdgs].sum(axis=1) == 1
sdg_sum_one_rows = sdg_17_only[sdg_sum_one]

sdg_sum_zero_rows

,text,SDG-01,SDG-02,SDG-03,SDG-04,SDG-05,SDG-06,SDG-07,SDG-08,SDG-09,SDG-10,SDG-11,SDG-12,SDG-13,SDG-14,SDG-15,SDG-16,SDG-17
2,VNR Update: 15 Countries Planning to Participa...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
12,Consultation Underway on New Indicator for SDG...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
35,More Inclusive Means More Complete: Report Sha...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
48,"Local SDG Action, Reporting Get Higher Profile...",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
56,HLPF Opens With Calls to Use 2030 Agenda to Bu...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9104,Side Event Highlights Efforts to Make SDG Data...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
9106,My Experience at the ECOSOC Youth Forum Youth ...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
9129,Why a Business School Should Want to be a Forc...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
9143,GIS for a Sustainable World: Bringing the Powe...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
9170,Generation 2030: Have Your Say The Generation ...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

SDG-17에만 해당하는 데이터: 616개

In [18]:
sdg_sum_one_rows

,text,SDG-01,SDG-02,SDG-03,SDG-04,SDG-05,SDG-06,SDG-07,SDG-08,SDG-09,SDG-10,SDG-11,SDG-12,SDG-13,SDG-14,SDG-15,SDG-16,SDG-17
15,2021 Population Data Sheet Highlights Declinin...,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1
29,ECOSOC President Offers Preview of 2022 Sessio...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
32,Peer Exchange Identifies Components of Good Ci...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
46,WTO Members Move Closer to Agreement on Fisher...,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1
49,WTO Members Endorse Extended TRIPS Transition ...,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9135,Community Momentum: Accelerating SDG Implement...,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1
9136,UNESCO Initiatives Examine Education for Susta...,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1
9138,UNICEF Highlights Young Climate Heroes as Winn...,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1
9150,The Essence of Leadership for Achieving the Su...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1
9161,Localizing the SDGs at the Grassroots in Niger...,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1

다른 SDG 중 하나를 포함하고, SDG-17==1을 만족하는 데이터: 803개

In [22]:
remaining_rows_count = 1100 - len(sdg_sum_zero_rows)

if remaining_rows_count > 0:
    selected_sdg_sum_one_rows = sdg_sum_one_rows.head(remaining_rows_count)
else:
    selected_sdg_sum_one_rows = pd.DataFrame()

# DataFrame concat
final_rows = pd.concat([sdg_sum_zero_rows, selected_sdg_sum_one_rows])
final_rows

,text,SDG-01,SDG-02,SDG-03,SDG-04,SDG-05,SDG-06,SDG-07,SDG-08,SDG-09,SDG-10,SDG-11,SDG-12,SDG-13,SDG-14,SDG-15,SDG-16,SDG-17
2,VNR Update: 15 Countries Planning to Participa...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
12,Consultation Underway on New Indicator for SDG...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
35,More Inclusive Means More Complete: Report Sha...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
48,"Local SDG Action, Reporting Get Higher Profile...",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
56,HLPF Opens With Calls to Use 2030 Agenda to Bu...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6605,"UNFF11 Discusses Implementation, Finance and P...",0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1
6607,FfD 3 Co-Facilitators Announce Additional Cons...,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
6612,High-level Consultation Agrees on FfD Action P...,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
6630,Civil Society Discusses Positioning of UN Deve...,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
6632,Report Identifies Lessons from MDGs for Post-2...,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

osdg 데이터에서 SDG 별로 존재하는 최소 데이터는 약 1100개 이므로 총 1100개의 SDG-17 데이터셋 정립

In [24]:
df_osdg

                                                    text  sdg
0      From a gender perspective, Paulgaard points ou...    5
1      Labour legislation regulates maximum working h...   11
2      The average figure also masks large difference...    3
3      Applied research is directed “primarily toward...    9
4      The extent to which they are akin to corruptio...    3
...                                                  ...  ...
42630  Since the full capacity is not likely to be ut...    7
42631  This article notes the judgment in Sophocleous...   16
42632  Groundwater quality can also be affected by co...    6
42633  Remedier a ces lacunes est la recommandation p...    2
42634  The three diseases that resulted in the greate...    3

[42635 rows x 2 columns]

In [25]:
final_rows_to_add = final_rows[['text']].copy()  
final_rows_to_add['sdg'] = 17 

df_osdg_updated = pd.concat([df_osdg, final_rows_to_add], ignore_index=True)
df_osdg_updated

                                                    text  sdg
0      From a gender perspective, Paulgaard points ou...    5
1      Labour legislation regulates maximum working h...   11
2      The average figure also masks large difference...    3
3      Applied research is directed “primarily toward...    9
4      The extent to which they are akin to corruptio...    3
...                                                  ...  ...
43730  UNFF11 Discusses Implementation, Finance and P...   17
43731  FfD 3 Co-Facilitators Announce Additional Cons...   17
43732  High-level Consultation Agrees on FfD Action P...   17
43733  Civil Society Discusses Positioning of UN Deve...   17
43734  Report Identifies Lessons from MDGs for Post-2...   17

[43735 rows x 2 columns]

In [26]:
df_osdg_updated.groupby('sdg').count()

     text
sdg
1    2734
2    2457
3    2689
4    3740
5    4338
6    2815
7    3048
8    1509
9    2510
10   2244
11   2277
12   1108
13   2102
14   1141
15   2472
16   5451
17   1100

In [27]:
df_osdg_updated.to_csv('./df_osdg_updated.csv', index=False)